---
version: '3.5'
services:

  rabbitmq:
    image: rabbitmq:3.8.19-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "8080:8080"
    environment:
      RABBITMQ_DEFAULT_USER: "myuser"
      RABBITMQ_DEFAULT_PASS: "mypassword"

  rabbitmq_producer:
    build:
      context: ../../connect/connect-rabbitmq-source/producer
    hostname: rabbitmq_producer
    container_name: rabbitmq_producer

  rabbitmq_consumer:
    build:
      context: ../../connect/connect-rabbitmq-source/consumer
    hostname: rabbitmq_consumer
    container_name: rabbitmq_consumer

  # https://github.com/shkoliar/docker-ngrok
  ngrok:
    image: shkoliar/ngrok:latest
    hostname: ngrok
    container_name: ngrok
    ports:
      - 4551:4551
    links:
      - rabbitmq
    environment:
      DOMAIN: rabbitmq
      PORT: 5672
      PROTOCOL: tcp
      REGION: eu
      AUTH_TOKEN: $NGROK_AUTH_TOKEN
      DEBUG: "true"