name: Update README

on:
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: vdesabou/kafka-docker-playground
          fetch-depth: 0
          token: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Decrypt secrets.tar
        run: |
          ./.github/scripts/decrypt_secret.sh
          tar xvf secrets.tar
          rm secrets.tar
          mkdir -p $HOME/.aws
          mv aws_config $HOME/.aws/config
          mv aws_credentials $HOME/.aws/credentials
          chmod -R a+rw $HOME/.aws
          mkdir -p $HOME/.confluent
          mv config.cc.travis $HOME/.confluent/config
          echo "$DOCKER_PASSWORD" | docker login -u vdesabou --password-stdin
        env:
          SECRETS_ENCRYPTION_PASSWORD: ${{ secrets.SECRETS_ENCRYPTION_PASSWORD }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}

      # - name: Update README
      #   run: |
      #     ./scripts/update-readme.sh "5.4.8 5.5.10 6.0.8 6.1.6 6.2.5 7.0.4 7.1.2"
      #   env:
      #     GH_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}


      - name: Pushes content.md
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.CI_GITHUB_TOKEN }}
        with:
          source_file: './docs/content.md'
          destination_repo: 'vdesabou/kafka-docker-playground-docs'
          destination_folder: 'docs'
          user_email: 'vincent.desaboulin@gmail.com'
          user_name: 'vdesabou'
          commit_message: 'updating with latest versions'

      - name: Pushes introduction.md
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.CI_GITHUB_TOKEN }}
        with:
          source_file: './docs/introduction.md'
          destination_repo: 'vdesabou/kafka-docker-playground-docs'
          destination_folder: 'docs'
          user_email: 'vincent.desaboulin@gmail.com'
          user_name: 'vdesabou'
          commit_message: 'updating with latest versions'

      # - name: push docs
      #   uses: actions-x/commit@v6
      #   with:
      #     token: ${{ secrets.CI_GITHUB_TOKEN }}
      #     repository: https://github.com/vdesabou/kafka-docker-playground-docs
      #     message: 'updating with latest versions'
      #     files: ./docs/content.md ./docs/introduction.md
      #     name: Vincent de Saboulin
      #     directory: docs